all:
  hosts:
    preprod:
      ansible_host: 192.168.140.50
      ansible_port: 22
      ansible_user: ubuntu
      ansible_ssh_extra_args: "-o ForwardAgent=yes -o IdentitiesOnly=yes"
      ansible_ssh_private_key_file: "{{ inventory_dir }}/p1925518-key.pem"
      ansible_python_interpreter: /usr/bin/python3
    prod:
      ansible_host: 192.168.140.20
      ansible_port: 22
      ansible_user: ubuntu
      ansible_ssh_extra_args: "-o ForwardAgent=yes -o IdentitiesOnly=yes"
      ansible_ssh_private_key_file: "{{ inventory_dir }}/p1925518-key.pem"
      ansible_python_interpreter: /usr/bin/python3
  children:
    webservers:
      hosts:
        preprod:
        prod:

