

- name: Clone app repo
  become_user: ubuntu
  git:
    repo: 'https://github.com/mierz00/flask-hello-world.git'
    dest: /home/ubuntu/flask-hello-world
    update: yes 
- name: Install python in a virtualenv
  pip:
    requirements: /home/ubuntu/flask-hello-world/requirements.txt
    virtualenv: /home/ubuntu/flask-hello-world/env
    virtualenv_python: python3.6.9