- name: Kill apt processes and correct dpkg
  become: yes
  become_method: sudo
  script: correct-packages.sh

- name: Install prerequisite packages
  apt:
      update_cache: yes
      name: "{{item}}"
      state: latest
  loop:
      - python3
      - python3-psycopg2
      - python3-pip

- name: Install virtualenv via pip
  pip:
      name: virtualenv
      executable: pip3
