
- name: Install prerequisite packages
  apt:
    update_cache: yes
    name: "{{item}}" 
    state: latest
  loop:
    - python3
    - python3-psycopg2
    - python3-pip

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3