- name: Get latest release version for production.
  shell: "git ls-remote --tags https://github.com/{{ git_user }}/{{ app_name }}.git | cut -d/ -f3- | sort -t. -nk1,2 -k3 | awk '/^[^{]*$/{version=$1}END{print version}'"
  register: latest_tag

- name: Clone app repo into releases
  git:
      repo: "https://github.com/{{ git_user }}/{{ app_name }}.git"
      dest: "/var/www/{{ app_name }}/releases/{{ latest_tag.stdout }}"
      depth: 1
      version: "{{ latest_tag.stdout }}"

- name: Copy welcome message to folder
  template:
      src: ./templates/message
      dest: "/var/www/{{ app_name }}/releases/{{ latest_tag.stdout }}/message.py"

- name: Install python packages in a virtualenv
  pip:
      requirements: "/var/www/{{ app_name }}/releases/{{ latest_tag.stdout }}/requirements.txt"
      virtualenv: "/var/www/{{ app_name }}/releases/{{ latest_tag.stdout }}/env"
      virtualenv_python: python3.6.9

- name: Create symbolic link to current
  file:
      src: "/var/www/{{ app_name }}/releases/{{ latest_tag.stdout }}"
      dest: "/var/www/{{ app_name }}/current"
      state: link
